image: ubuntu:latest

stages:
  - build

before_script:
  - chmod +x cpwrapper
  - env DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1
build:
  stage: build
  script:
    ./cpwrapper build
  artifacts:
    paths:
      - build/
    expire_in: 1 week