image: ubuntu:latest

stages:
  - build

before_script:
  - apt install libicu70
  - chmod +x cpwrapper

build:
  stage: build
  script:
    ./cpwrapper build
  artifacts:
    paths:
      - build/
    expire_in: 1 week