modLoader="lowcodefml"
loaderVersion="[40,)"
logoFile="pack.png"
logoBlur=false
license="AGPL"
[[mods]]
    modId="arcore"
    version="0.0.2"
    displayName="ArCore"
    description='''
    Arcadia Core Mod
    '''
[[dependencies.arcore]]
    modId="forge"
    mandatory=true
    versionRange="[40.1.40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.arcore]]
    modId="quarkoddities"
    mandatory=true
    versionRange="[1.20.1,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.arcore]]
    modId="jsonthings"
    mandatory=true
    versionRange="[0.4.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.arcore]]
    modId="patched"
    mandatory=true
    versionRange="[3.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.arcore]]
    modId="lychee"
    mandatory=true
    versionRange="[5.1.0,)"
    ordering="NONE"
    side="BOTH"